version: '3'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    network_mode: bridge
    volumes:
      - ./ml_dash_kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
